let button = false
game.setGameOverEffect(true, effects.bubbles)
game.setGameOverEffect(false, effects.bubbles)
game.setGameOverPlayable(true, music.melodyPlayable(music.powerUp), true)
game.setGameOverPlayable(false, music.melodyPlayable(music.wawawawaa), true)
let gravity = 2.5
let speed = 1
let jump_height = 200
scene.setBackgroundColor(8)
effects.bubbles.startScreenEffect()
let mySprite = sprites.create(img`
    ..............fffcc.............
    ..............fcbddcc...........
    ...............fbbddcc..........
    ...............fcbbccf..........
    ..ccc.........ffccccccfffff.....
    ..cbbcc....fffcbbbbcbbbbbbbff...
    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
    ...fbbdcfcccccbbbcbcbbffbbbbbbff
    ....fbbffcccccbbbbbcb1ff11bbbcbf
    ....fcbbcccccccbbbbb11111111bbbf
    ....fcccccccccccbbbb11cc33111bf.
    ...fcbbffbdbcccccbbb111c13cccf..
    ...fbbf..ccddddcfbbbc111c31cf...
    ..fbbf.....ccdccbbdbf111cccf....
    ..fff........ccbbdcfcccc........
    ..............fffff.............
    `, SpriteKind.Player)
mySprite.startEffect(effects.bubbles)
mySprite.x = 25
animation.runImageAnimation(
mySprite,
[img`
    ..............fffcc.............
    ..............fcbddcc...........
    ...............fbbddcc..........
    ...............fcbbccf..........
    ..ccc.........ffccccccfffff.....
    ..cbbcc....fffcbbbbcbbbbbbbff...
    ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
    ...fbbdcfcccccbbbcbcbbffbbbbbbff
    ....fbbffcccccbbbbbcb1ff11bbbcbf
    ....fcbbcccccccbbbbb11111111bbbf
    ....fcccccccccccbbbb11cc33111bf.
    ...fcbbffbdbcccccbbb111c13cccf..
    ...fbbf..ccddddcfbbbc111c31cf...
    ..fbbf.....ccdccbbdbf111cccf....
    ..fff........ccbbdcfcccc........
    ..............fffff.............
    `,img`
    ..............fffcc.............
    ..............fbbddc............
    ...............fbbddc...........
    ccc............fcbbccf..........
    cbbcc.........ffccccccffffff....
    .cbbdc.....fffcbbbbbbbbbbbbbff..
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
    ..fcbbbcccccccbbbcbcb1ff1111bbbf
    ..fccbcccccccccbbbbbb11111111bf.
    .fcbbfffccccccccbbbb11cc33cccf..
    .fbbf...cbdbcccccbbb111c131cf...
    fbbf.....ccdddddfbbbc111c33f....
    fff........ccddfbbdbf1111ff.....
    .............cfbbdbfccccc.......
    ..............fffff.............
    `,img`
    ..............fffc..............
    ..............fbddcc............
    ..ccc.........ffbddbc...........
    ..cbbc.........fcbbccf..........
    ...cbdc.......ffccccccfffffff...
    ...fbdc....fffcbbbbbbbbbbbbbcff.
    ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
    ....fcdffcccccbbbcbcbbbffbbbbcbf
    ....fcbbccccccbbbcbcbbbff1111bbf
    ...fcbbccccccccbbbcbb11111111bf.
    ...fbbfffcccccccbbbb11bc33cccf..
    ..fbbf..cbdbcccccbbb111c131cf...
    ..fff....cbdddddccbbc111c33f....
    ..........ccbddccbbdf1111ff.....
    ............ccfbbbdfccccc.......
    ..............fffff.............
    `,img`
    ..............fffcc.............
    ..............fbbddc............
    ...............fbbddc...........
    ccc............fcbbccf..........
    cbbcc.........ffccccccffffff....
    .cbbdc.....fffcbbbbbbbbbbbbbff..
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
    ..fcbbbcccccccbbbcbcb1ff1111bbbf
    ..fccbcccccccccbbbbbb11111111bf.
    .fcbbfffccccccccbbbb11cc33cccf..
    .fbbf...cbdbcccccbbb111c131cf...
    fbbf.....ccdddddfbbbc111c33f....
    fff........ccddfbbdbf1111ff.....
    .............cfbbdbfccccc.......
    ..............fffff.............
    `],
100,
true
)
forever(function () {
    let gravity_math: number;
let score: number;
let jump_math: number;
if (controller.anyButton.isPressed()) {
        button = true
    } else {
        button = false
    }
    if (button == false) {
        gravity_math = 0
        gravity_math = (mySprite.vy + (mySprite.y - 0)) / gravity
        mySprite.setVelocity(0, gravity_math)
    }
    if (mySprite.y >= 120 || mySprite.y <= 0) {
        score = (gravity + speed) / 2
        game.gameOver(false)
    }
    if (button == true) {
        jump_math = 0
        jump_math = jump_height / speed
        music.play(music.melodyPlayable(music.buzzer), music.PlaybackMode.InBackground)
        mySprite.setVelocity(0, 0 - jump_math)
    }
})
