button = False
gravity = 2.5
speed = 1
jump_height = 200
scene.set_background_color(8)
effects.bubbles.start_screen_effect()
mySprite = sprites.create(img("""
        ..............fffcc.............
        ..............fcbddcc...........
        ...............fbbddcc..........
        ...............fcbbccf..........
        ..ccc.........ffccccccfffff.....
        ..cbbcc....fffcbbbbcbbbbbbbff...
        ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
        ...fbbdcfcccccbbbcbcbbffbbbbbbff
        ....fbbffcccccbbbbbcb1ff11bbbcbf
        ....fcbbcccccccbbbbb11111111bbbf
        ....fcccccccccccbbbb11cc33111bf.
        ...fcbbffbdbcccccbbb111c13cccf..
        ...fbbf..ccddddcfbbbc111c31cf...
        ..fbbf.....ccdccbbdbf111cccf....
        ..fff........ccbbdcfcccc........
        ..............fffff.............
        """),
    SpriteKind.player)
mySprite.start_effect(effects.bubbles)
mySprite.x = 25
animation.run_image_animation(mySprite,
    [img("""
            ..............fffcc.............
            ..............fcbddcc...........
            ...............fbbddcc..........
            ...............fcbbccf..........
            ..ccc.........ffccccccfffff.....
            ..cbbcc....fffcbbbbcbbbbbbbff...
            ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
            ...fbbdcfcccccbbbcbcbbffbbbbbbff
            ....fbbffcccccbbbbbcb1ff11bbbcbf
            ....fcbbcccccccbbbbb11111111bbbf
            ....fcccccccccccbbbb11cc33111bf.
            ...fcbbffbdbcccccbbb111c13cccf..
            ...fbbf..ccddddcfbbbc111c31cf...
            ..fbbf.....ccdccbbdbf111cccf....
            ..fff........ccbbdcfcccc........
            ..............fffff.............
            """),
        img("""
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            """),
        img("""
            ..............fffc..............
            ..............fbddcc............
            ..ccc.........ffbddbc...........
            ..cbbc.........fcbbccf..........
            ...cbdc.......ffccccccfffffff...
            ...fbdc....fffcbbbbbbbbbbbbbcff.
            ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
            ....fcdffcccccbbbcbcbbbffbbbbcbf
            ....fcbbccccccbbbcbcbbbff1111bbf
            ...fcbbccccccccbbbcbb11111111bf.
            ...fbbfffcccccccbbbb11bc33cccf..
            ..fbbf..cbdbcccccbbb111c131cf...
            ..fff....cbdddddccbbc111c33f....
            ..........ccbddccbbdf1111ff.....
            ............ccfbbbdfccccc.......
            ..............fffff.............
            """),
        img("""
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            """)],
    100,
    True)

def on_forever():
    global button
    if controller.any_button.is_pressed():
        button = True
    else:
        button = False
    if button == False:
        gravity_math = 0
        gravity_math = (mySprite.vy + (mySprite.y - 0)) / gravity
        mySprite.set_velocity(0, gravity_math)
    if mySprite.y >= 120 or mySprite.y <= 0:
        score = (gravity + speed) / 2
        game.game_over(False)
    if button == True:
        jump_math = 0
        jump_math = jump_height / speed
        mySprite.set_velocity(0, 0 - jump_math)
forever(on_forever)
